///////////////////////////////////////////////////////////
//  WeatherStateCollector.cs
//  Implementation of the Class WeatherStateCollector
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.32.21
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherCommon.Classes;
using WeatherWorkerRoleData.Classes;

namespace WeatherCollector.Classes {
	public class WeatherStateCollector {

		private IWeather proxy;
		private Dictionary<string,Weather> weatherStates;

		public WeatherStateCollector(){ 
            weatherStates = new Dictionary<string, Weather>();
		}

		public void ConnectToServicehost(){

		}

		public void GetStatesFromWeb(){

		}

		public void SendStatesToWorkerRole(){

		}

	}//end WeatherStateCollector

}//end namespace WeatherCollector