///////////////////////////////////////////////////////////
//  INotify.cs
//  Implementation of the Interface INotify
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace WeatherCommon.Classes
{
    [ServiceContract]
	public interface INotify  {

		/// 
		/// <param name="weatherName"></param>
        [OperationContract]
		bool NotifyWeatherStateChanged(string weatherName);
	}//end INotify

}//end namespace WeatherCommon