///////////////////////////////////////////////////////////
//  WindGenerator.cs
//  Implementation of the Class WindGenerator
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherWorkerRoleData.Classes;

namespace WeatherCommon.Classes
{
	public class WindGenerator {

		private double coefficient;
		private double power;
		private double turbineDiameter;
		private Weather weather;

		public WindGenerator(){

		}

        public WindGenerator(double coefficient, double power, double turbineDiameter, Weather weather)
        {
            this.Coefficient = coefficient;
            this.Power = power;
            this.TurbineDiameter = turbineDiameter;
            this.Weather = weather;
        }

        public double Coefficient { get => coefficient; set => coefficient = value; }
        public double Power { get => power; set => power = value; }
        public double TurbineDiameter { get => turbineDiameter; set => turbineDiameter = value; }
        public Weather Weather { get => weather; set => weather = value; }

        public double CalculatePower(){

			return 0;
		}

	}//end WindGenerator

}//end namespace WeatherCommon