///////////////////////////////////////////////////////////
//  WindGenerator.cs
//  Implementation of the Class WindGenerator
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherWorkerRoleData.Classes;

namespace WeatherCommon.Classes
{
	public class WindGenerator {

		private double coefficient;
		private double power;
		private double turbineDiameter;
		private Weather weather;
        private double maxSpeed;

		public WindGenerator(){

		}

        public WindGenerator(double coefficient, double power, double turbineDiameter, Weather weather, double maxSpeed)
        {
            this.Coefficient = coefficient;
            this.Power = power;
            this.TurbineDiameter = turbineDiameter;
            this.Weather = weather;
            this.MaxSpeed = maxSpeed;
        }

        public double Coefficient { get => coefficient; set => coefficient = value; }
        public double Power { get => power; set => power = value; }
        public double TurbineDiameter { get => turbineDiameter; set => turbineDiameter = value; }
        public Weather Weather { get => weather; set => weather = value; }
        public double MaxSpeed { get => maxSpeed; set => maxSpeed = value; }

        public double CalculateSurfaceArea()
        {
            return Math.Pow((TurbineDiameter / 2), 2) * Math.PI;
        }

        public double CalculatePower()
        {
            double power = 0.5 * Weather.AirDensity * CalculateSurfaceArea() * Math.Pow(Weather.WindSpeed, 3);

			return power * Coefficient;
		}

	}//end WindGenerator

}//end namespace WeatherCommon