///////////////////////////////////////////////////////////
//  Admin.cs
//  Implementation of the Class Admin
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.27.52
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using LiveCharts.Geared;

namespace WeatherAdminWPF.Classes {
	public class Admin {
        
        public Admin(){
            
		}

		~Admin(){

		}

	}//end Admin

}//end namespace WeatherAdminWPF