///////////////////////////////////////////////////////////
//  ReplicatorJobServer.cs
//  Implementation of the Class ReplicatorJobServer
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.30.39
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Project.WeatherCloudService.WeatherReplicatorWorkerRole;
namespace Project.WeatherCloudService.WeatherReplicatorWorkerRole {
	public class ReplicatorJobServer {

		public ReplicatorJobServer(){

		}

		~ReplicatorJobServer(){

		}

	}//end ReplicatorJobServer

}//end namespace WeatherReplicatorWorkerRole