///////////////////////////////////////////////////////////
//  ReplicatorJobServerProvider.cs
//  Implementation of the Class ReplicatorJobServerProvider
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.30.39
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace WeatherReplicatorWorkerRole.Classes
{
	public class ReplicatorJobServerProvider {

		public ReplicatorJobServerProvider(){

		}

		~ReplicatorJobServerProvider(){

		}

	}//end ReplicatorJobServerProvider

}//end namespace WeatherReplicatorWorkerRole