///////////////////////////////////////////////////////////
//  WeatherJobServer.cs
//  Implementation of the Class WeatherJobServer
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.24
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Project.WeatherCloudService.WeatherWorkerRole;
namespace Project.WeatherCloudService.WeatherWorkerRole {
	public class WeatherJobServer {

		public WeatherJobServer(){

		}

		~WeatherJobServer(){

		}

	}//end WeatherJobServer

}//end namespace WeatherWorkerRole