///////////////////////////////////////////////////////////
//  IWeather.cs
//  Implementation of the Interface IWeather
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace WeatherCommon.Classes
{
    [ServiceContract]
    public interface IWeather
    {




        /// <summary>
        /// parametar mozda da bude cela lista
        /// </summary>
        /// <param name="weather"></param>
        [OperationContract]
        void SendWeatherState(Weather weather);

        [OperationContract]
        WindGenerator GetWindGenerator();
    }//end IWeather

}//end namespace WeatherCommon