///////////////////////////////////////////////////////////
//  WeatherJobServerProvider.cs
//  Implementation of the Class WeatherJobServerProvider
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.24
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherCommon.Classes;
using System.Diagnostics;

namespace WeatherWorkerRole.Classes
{
	public class WeatherJobServerProvider : IWeather
    {
        private Dictionary<string, Weather> weathers = new Dictionary<string, Weather>();
		public WeatherJobServerProvider(){

		}

		~WeatherJobServerProvider(){

		}

        public void SendWeatherState(Weather weather)
        {
            if(!weathers.ContainsKey(weather.City))
            {
                weathers.Add(weather.City, weather);
                Trace.WriteLine(weather);
            }
            else
            {
                weathers[weather.City] = weather;
                Trace.WriteLine(weather);
            }

            Trace.WriteLine(new WindGenerator(0.35, 10000000, 50, weather, 18, 10).CalculatePower());
        }

    }//end WeatherJobServerProvider

}//end namespace WeatherWorkerRole