///////////////////////////////////////////////////////////
//  WeatherJobServerProvider.cs
//  Implementation of the Class WeatherJobServerProvider
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.24
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherCommon.Classes;
using System.Diagnostics;

namespace WeatherWorkerRole.Classes
{
	public class WeatherJobServerProvider : IWeather
    {
        private Dictionary<string, Weather> dictionary = new Dictionary<string, Weather>();

		public WeatherJobServerProvider(){

		}

		~WeatherJobServerProvider(){

		}

        public void SendWeatherState(Weather weather)
        {
            if(!dictionary.ContainsKey(weather.City))
            {
                dictionary.Add(weather.City, weather);
                Trace.WriteLine(weather);
            }
        }

    }//end WeatherJobServerProvider

}//end namespace WeatherWorkerRole