///////////////////////////////////////////////////////////
//  Aggregate.cs
//  Implementation of the Class Aggregate
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.04
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCommon {
	public class Aggregate {

		private double costPerKwh;
		private double power;
		private bool state;

		public Aggregate(){

		}

		~Aggregate(){

		}

	}//end Aggregate

}//end namespace WeatherCommon