///////////////////////////////////////////////////////////
//  Firm.cs
//  Implementation of the Class Firm
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCommon {
	public class Firm {

		private Aggregate aggregate;
		private string Name;
		private WindGenerator windGenerator;
		private int windmillCount;

		public Firm(){

		}

		~Firm(){

		}

	}//end Firm

}//end namespace WeatherCommon