///////////////////////////////////////////////////////////
//  WindGenerator.cs
//  Implementation of the Class WindGenerator
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCommon {
	public class WindGenerator {

		private double coefficient;
		private double power;
		private double turbineDiameter;
		private Weather weather;

		public WindGenerator(){

		}

		~WindGenerator(){

		}

		public double CalculatePower(){

			return 0;
		}

	}//end WindGenerator

}//end namespace WeatherCommon