///////////////////////////////////////////////////////////
//  WeatherStateCollector.cs
//  Implementation of the Class WeatherStateCollector
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.32.21
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCollector {
	public class WeatherStateCollector {

		private IWeather proxy;
		private Weather Dictionary weatherStates;

		public WeatherStateCollector(){

		}

		~WeatherStateCollector(){

		}

		public void ConnectToServicehost(){

		}

		public void GetStatesFromWeb(){

		}

		public void SendStatesToWorkerRole(){

		}

	}//end WeatherStateCollector

}//end namespace WeatherCollector