///////////////////////////////////////////////////////////
//  WeatherRepository.cs
//  Implementation of the Class WeatherRepository
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.48
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace WeatherWorkerRoleData.Classes
{
	public class WeatherRepository {

		public WeatherRepository(){

		}

		~WeatherRepository(){

		}

	}//end WeatherRepository

}//end namespace WeatherWorkerRoleData