///////////////////////////////////////////////////////////
//  Weather.cs
//  Implementation of the Class Weather
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.48
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherCommon.Classes;

namespace WeatherWorkerRoleData.Classes
{
	public class WindGeneratorBase  { // :TableEntity

        private double coefficient;
        private double minPower;
        private double turbineDiameter;
        private Weather weather;
        private double maxSpeed;
        private int maxSpeedTime;
        private Aggregate aggregate;
        private double power;
        private int windMillCnt;
        private int workingTime = 0;

        public double Coefficient { get => coefficient; set => coefficient = value; }
        public double MinPower { get => minPower; set => minPower = value; }
        public double TurbineDiameter { get => turbineDiameter; set => turbineDiameter = value; }
        public Weather Weather { get => weather; set => weather = value; }
        public double MaxSpeed { get => maxSpeed; set => maxSpeed = value; }
        public int MaxSpeedTime { get => maxSpeedTime; set => maxSpeedTime = value; }
        public Aggregate Aggregate { get => aggregate; set => aggregate = value; }
        public double Power { get => CalculatePower(); set => power = value; }
        public int WorkingTime { get => workingTime; set => workingTime = value; }
        public int WindMillCnt { get => windMillCnt; set => windMillCnt = value; }

        public WindGeneratorBase()
        {

        }



        public WindGeneratorBase(double coefficient, double minPower, double turbineDiameter, Weather weather, double maxSpeed, int maxSpeedTime,int windmillcnt, Aggregate aggregate)
        {
            //PartitionKey = "WindGenerator";
            //RowKey =  weather.City;
            this.coefficient = coefficient;
            this.minPower = minPower;
            this.turbineDiameter = turbineDiameter;
            this.weather = weather;
            this.maxSpeed = maxSpeed;
            this.maxSpeedTime = maxSpeedTime;
            this.WindMillCnt = windmillcnt;
            this.aggregate = aggregate;
            this.power = CalculatePower();
        }

        public double CalculateSurfaceArea()
        {
            return Math.Pow((TurbineDiameter / 2), 2) * Math.PI;
        }

        /// <summary>
        /// Metoda se poziva u okviru nekog while-a, pa ce ovo WorkingTime++ imati nekog smisla
        /// </summary>
        /// <returns></returns>
        private double CalculatePower()
        {
            double power = 0;

            if (Weather.WindSpeed >= MaxSpeed && WorkingTime >= MaxSpeedTime)
            {
                power = 0;

            }
            else if (Weather.WindSpeed >= MaxSpeed && WorkingTime < MaxSpeedTime)
            {
                power = 0.5 * Coefficient * Weather.AirDensity * CalculateSurfaceArea() * Math.Pow(Weather.WindSpeed, 3);
                WorkingTime++;
            }
            else
            {
                power = 0.5 * Coefficient * Weather.AirDensity * CalculateSurfaceArea() * Math.Pow(Weather.WindSpeed, 3);
                WorkingTime = 0;
            }

            if (WorkingTime == MaxSpeedTime + (MaxSpeedTime / 2)) // cooling period
            {
                WorkingTime = 0;
            }
            return power;
        }
    }//end Weather

}//end namespace WeatherWorkerRoleData