///////////////////////////////////////////////////////////
//  View.cs
//  Implementation of the Class View
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.03
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Project.WeatherCloudService.WeatherWebRole;
namespace Project.WeatherCloudService.WeatherWebRole {
	public class View {

		public View(){

		}

		~View(){

		}

	}//end View

}//end namespace WeatherWebRole