///////////////////////////////////////////////////////////
//  Admin.cs
//  Implementation of the Class Admin
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.27.52
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WeatherCommon.Classes;
using System.ServiceModel;

namespace WeatherAdminWPF.Classes {
	public class Admin : INotify {

		public Admin(){
            
		}

		~Admin(){

		}

        public bool NotifyWeatherStateChanged(string weatherName)
        {
            if (weatherName.Equals("Novi Sad"))
                return true;
            else
                return false;   
        }
    }//end Admin

}//end namespace WeatherAdminWPF