///////////////////////////////////////////////////////////
//  ReplicatorRepository.cs
//  Implementation of the Class ReplicatorRepository
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.30.12
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCloudService.WeatherReplicatorData {
	public class ReplicatorRepository {

		public ReplicatorRepository(){

		}

		~ReplicatorRepository(){

		}

	}//end ReplicatorRepository

}//end namespace WeatherReplicatorData