///////////////////////////////////////////////////////////
//  WeatherJobServerProvider.cs
//  Implementation of the Class WeatherJobServerProvider
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.31.24
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCloudService.WeatherWorkerRole {
	public class WeatherJobServerProvider {

		public WeatherJobServerProvider(){

		}

		~WeatherJobServerProvider(){

		}

	}//end WeatherJobServerProvider

}//end namespace WeatherWorkerRole