///////////////////////////////////////////////////////////
//  INotify.cs
//  Implementation of the Interface INotify
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCommon {
	public interface INotify  {

		/// 
		/// <param name="weatherName"></param>
		bool NotifyWeatherStateChanged(string weatherName);
	}//end INotify

}//end namespace WeatherCommon