///////////////////////////////////////////////////////////
//  IWeather.cs
//  Implementation of the Interface IWeather
//  Generated by Enterprise Architect
//  Created on:      16-maj-2018 10.33.05
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Project.WeatherCommon {
	public interface IWeather  {

		/// <summary>
		/// parametar mozda da bude cela lista
		/// </summary>
		/// <param name="weather"></param>
		void SendWeatherState(Weather weather);
	}//end IWeather

}//end namespace WeatherCommon